kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: tasks-pipeline
  spec:
  nodeSelector: {}
  output: {}
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
spec:
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: openshift-tasks/Jenkinsfile
      #jenkinsfilePath: JENKINS_FILE_PATH
  postCommit: {}
  source:
    type: Git
    git:
      #uri: GIT_REPO
      uri:  https://github.com/naveenkendyala/ocp-jenkins-pipeline-demo.git              
  triggers: []
  runPolicy: Serial
